# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcLDFRAME(wx.Dialog):
#!XRCED:begin-block:xrcLDFRAME.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcLDFRAME.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "LDFRAME")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.LD_LOAD_SOURCE = xrc.XRCCTRL(self, "LD_LOAD_SOURCE")
        self.POST_L_ItemSourceLabel = xrc.XRCCTRL(self, "POST_L_ItemSourceLabel")
        self.POST_L_ItemSource = xrc.XRCCTRL(self, "POST_L_ItemSource")
        self.POST_L_ItemSelSingle = xrc.XRCCTRL(self, "POST_L_ItemSelSingle")
        self.POST_L_ItemSingle = xrc.XRCCTRL(self, "POST_L_ItemSingle")
        self.POST_L_ItemSelList = xrc.XRCCTRL(self, "POST_L_ItemSelList")
        self.POST_L_ItemList = xrc.XRCCTRL(self, "POST_L_ItemList")
        self.POST_L_ItemSelSet = xrc.XRCCTRL(self, "POST_L_ItemSelSet")
        self.POST_L_ItemSet = xrc.XRCCTRL(self, "POST_L_ItemSet")
        self.POST_D_ItemSourceLabel = xrc.XRCCTRL(self, "POST_D_ItemSourceLabel")
        self.POST_D_ItemSource = xrc.XRCCTRL(self, "POST_D_ItemSource")
        self.POST_D_ItemSelSingle = xrc.XRCCTRL(self, "POST_D_ItemSelSingle")
        self.POST_D_ItemSingle = xrc.XRCCTRL(self, "POST_D_ItemSingle")
        self.POST_D_ItemSelList = xrc.XRCCTRL(self, "POST_D_ItemSelList")
        self.POST_D_ItemList = xrc.XRCCTRL(self, "POST_D_ItemList")
        self.POST_D_ItemSelSet = xrc.XRCCTRL(self, "POST_D_ItemSelSet")
        self.POST_D_ItemSet = xrc.XRCCTRL(self, "POST_D_ItemSet")
        self.POST_LD_QUICKPLOT = xrc.XRCCTRL(self, "POST_LD_QUICKPLOT")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    loaddisp_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="LDFRAME">
    <title>Quck Plot: Load Versus Displacement</title>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>2</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxRadioBox" name="LD_LOAD_SOURCE">
                  <label>Load Source</label>
                  <content>
                    <item>Load from time</item>
                    <item>Load From Reactions</item>
                  </content>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Reaction </label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>2</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="POST_L_ItemSourceLabel">
                      <label>Reaction Type</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_L_ItemSource">
                      <content>
                        <item>Reaction Force X</item>
                        <item>Reaction Force Y</item>
                        <item>Reaction Force Z</item>
                        <item>Reaction Moment X</item>
                        <item>Reaction Moment Y</item>
                        <item>Reaction Moment Z</item>
                      </content>
                      <selection>0</selection>
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelSingle">
                      <label>Single Item</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_L_ItemSingle">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelList">
                      <label>Item List</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_L_ItemList">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelSet">
                      <label>Item Set</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_L_ItemSet">
                      <content/>
                    </object>
                  </object>
                </object>
                <border>5</border>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Displacement</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>2</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="POST_D_ItemSourceLabel">
                      <label>Displacement Type</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_D_ItemSource">
                      <content>
                        <item>Displacement X</item>
                        <item>Displacement Y</item>
                        <item>Displacement Z</item>
                        <item>Rotation X</item>
                        <item>Rotation Y</item>
                        <item>Rotation Z</item>
                      </content>
                      <selection>0</selection>
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelSingle">
                      <label>Single Item</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_D_ItemSingle">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelList">
                      <label>Item List</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_D_ItemList">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelSet">
                      <label>Item Set</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_D_ItemSet">
                      <content/>
                    </object>
                  </object>
                </object>
                <border>5</border>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>2</cols>
              <rows>2</rows>
              <object class="spacer">
                <size>0,0</size>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="POST_LD_QUICKPLOT">
                  <label>Quick Plot</label>
                </object>
                <flag>wxALIGN_RIGHT</flag>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>0</border>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/loaddisp/loaddisp_xrc', loaddisp_xrc)
    __res.Load('memory:XRC/loaddisp/loaddisp_xrc')

