# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrchybrid(wx.Dialog):
#!XRCED:begin-block:xrchybrid.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrchybrid.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "hybrid")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.PARA_H = xrc.XRCCTRL(self, "PARA_H")
        self.PARA_B = xrc.XRCCTRL(self, "PARA_B")
        self.PARA_t1 = xrc.XRCCTRL(self, "PARA_t1")
        self.PARA_t2 = xrc.XRCCTRL(self, "PARA_t2")
        self.PARA_b3 = xrc.XRCCTRL(self, "PARA_b3")
        self.PARA_a = xrc.XRCCTRL(self, "PARA_a")
        self.PARA_L = xrc.XRCCTRL(self, "PARA_L")
        self.MESH_B = xrc.XRCCTRL(self, "MESH_B")
        self.MESH_H = xrc.XRCCTRL(self, "MESH_H")
        self.MESH_L = xrc.XRCCTRL(self, "MESH_L")
        self.PoleProcess = xrc.XRCCTRL(self, "PoleProcess")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    hybridsystem_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="hybrid">
    <title>Hybrid System</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxSYSTEM_MENU</style>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Geometries</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Total Height</label>
                    </object>
                    <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                  </object>
                  <rows>8</rows>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_H">
                      <value>4.875</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Width</label>
                    </object>
                    <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_B">
                      <value>10</value>
                      <style/>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Conrete Thinkness</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_t1">
                      <value>0.5</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Offset oh Concrete Layer</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_t2">
                      <value>0.125</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Top Side Width (b3)</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_b3">
                      <value>1.375</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Incline Angle (deg)</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_a">
                      <value>60.8</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Total Length</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_L">
                      <value>50</value>
                    </object>
                  </object>
                </object>
                <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
              </object>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Mesh Control</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>7</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Mesh Size B Direction</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="MESH_B">
                      <value>0.5</value>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Mesh Size H Direction</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="MESH_H">
                      <value>0.25</value>
                    </object>
                  </object>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Mesh Size L Direction</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="MESH_L">
                      <value>2.0</value>
                    </object>
                  </object>
                </object>
                <flag>wxEXPAND</flag>
              </object>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>1</rows>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxButton">
                      <label>Help</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="PoleProcess">
                      <label>Process</label>
                    </object>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxALIGN_RIGHT</flag>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/hybridsystem/hybridsystem_xrc', hybridsystem_xrc)
    __res.Load('memory:XRC/hybridsystem/hybridsystem_xrc')

