# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcMainFrame(wx.Frame):
#!XRCED:begin-block:xrcMainFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcMainFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "MainFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.MAIN_TOOLBAR_FILE = xrc.XRCCTRL(self, "MAIN_TOOLBAR_FILE")
        self.MAIN_TOOL_NEW = self.GetToolBar().FindById(xrc.XRCID("MAIN_TOOL_NEW"))
        self.MAIN_TOOL_OPEN = self.GetToolBar().FindById(xrc.XRCID("MAIN_TOOL_OPEN"))
        self.MAIN_TOOL_SAVE = self.GetToolBar().FindById(xrc.XRCID("MAIN_TOOL_SAVE"))
        self.MAIN_TOOL_SAVEAS = self.GetToolBar().FindById(xrc.XRCID("MAIN_TOOL_SAVEAS"))
        self.Menubar = self.GetMenuBar()
        idx = self.GetMenuBar().FindMenu("File")
        if idx != wx.NOT_FOUND:
            self.Menu_File = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_File = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_File")).GetSubMenu()
        self.MenuItem_New = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_New"))
        self.MenuItem_Open = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Open"))
        self.MenuItem_Close = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Close"))
        self.MenuItem_Save = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Save"))
        idx = self.GetMenuBar().FindMenu("FEM")
        if idx != wx.NOT_FOUND:
            self.Menu_FEM = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_FEM = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_FEM")).GetSubMenu()
        self.MenuItem_GridAdd = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_GridAdd"))
        self.MenuItem_Grid = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Grid"))
        self.MenuItem_Conn = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Conn"))
        self.MenuItem_Prop = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Prop"))
        self.MenuItem_Sec = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Sec"))
        self.MenuItem_Set = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Set"))
        idx = self.GetMenuBar().FindMenu("Utility")
        if idx != wx.NOT_FOUND:
            self.Menu_Utility = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Utility = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Utility")).GetSubMenu()
        self.MenuItem_Patch = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Patch"))
        idx = self.GetMenuBar().FindMenu("Material")
        if idx != wx.NOT_FOUND:
            self.MenuItem_Material = self.GetMenuBar().GetMenu(idx)
        else:
            self.MenuItem_Material = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Material")).GetSubMenu()
        self.MenuItem_Material_Interface = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Material_Interface"))
        self.MenuItem_Section = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Section"))
        self.MenuItem_Rebar = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Rebar"))
        idx = self.GetMenuBar().FindMenu("Import")
        if idx != wx.NOT_FOUND:
            self.Menu_Import = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Import = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Import")).GetSubMenu()
        self.MenuItem_ImpMarcDat = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_ImpMarcDat"))
        self.MenuItem_ImpPlain = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_ImpPlain"))
        idx = self.GetMenuBar().FindMenu("Export")
        if idx != wx.NOT_FOUND:
            self.Menu_Export = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Export = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Export")).GetSubMenu()
        self.MenuItem_ExpMarcProc = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_ExpMarcProc"))
        self.MenuItem_ExpMarcDat = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_ExpMarcDat"))
        self.MenuItem_ExpOpenSees = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_ExpOpenSees"))
        idx = self.GetMenuBar().FindMenu("PostProcess")
        if idx != wx.NOT_FOUND:
            self.Menu_Post = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Post = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Post")).GetSubMenu()
        self.MenuItem_PostResults = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_PostResults"))
        self.MenuItem_PostMarcT16 = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_PostMarcT16"))
        idx = self.GetMenuBar().FindMenu("Procedure")
        if idx != wx.NOT_FOUND:
            self.Menu_Proc = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Proc = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Proc")).GetSubMenu()
        self.MenuItem_Pole = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_Pole"))
        idx = self.GetMenuBar().FindMenu("Macro")
        if idx != wx.NOT_FOUND:
            self.Menu_Macro = self.GetMenuBar().GetMenu(idx)
        else:
            self.Menu_Macro = self.GetMenuBar().FindItemById(xrc.XRCID("Menu_Macro")).GetSubMenu()
        self.MenuItem_MacroRecord = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_MacroRecord"))
        self.MenuItem_MacroStop = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_MacroStop"))
        self.MenuItem_MacroSave = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_MacroSave"))
        self.MenuItem_MacroLoad = self.GetMenuBar().FindItemById(xrc.XRCID("MenuItem_MacroLoad"))
        self.MAIN_TOOL_MODELREFRESH = xrc.XRCCTRL(self, "MAIN_TOOL_MODELREFRESH")
        self.MAIN_TOOL_EXPAND = xrc.XRCCTRL(self, "MAIN_TOOL_EXPAND")
        self.MAIN_TOOL_COLLAPSE = xrc.XRCCTRL(self, "MAIN_TOOL_COLLAPSE")
        self.ModelTree = xrc.XRCCTRL(self, "ModelTree")
        self.ModelNoteBookPanel = xrc.XRCCTRL(self, "ModelNoteBookPanel")
        self.MAIN_MACRO_RECORD = xrc.XRCCTRL(self, "MAIN_MACRO_RECORD")
        self.MAIN_MACRO_STOP = xrc.XRCCTRL(self, "MAIN_MACRO_STOP")
        self.MAIN_MACRO_SAVE = xrc.XRCCTRL(self, "MAIN_MACRO_SAVE")
        self.MAIN_MACRO_LOAD = xrc.XRCCTRL(self, "MAIN_MACRO_LOAD")
        self.TextMessage = xrc.XRCCTRL(self, "TextMessage")
        self.MAIN_STATUSBAR = xrc.XRCCTRL(self, "MAIN_STATUSBAR")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    MainFrame_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="MainFrame">
    <title>Webfe</title>
    <object class="wxToolBar" name="MAIN_TOOLBAR_FILE">
      <object class="tool" name="MAIN_TOOL_NEW">
        <bitmap stock_id="wxART_NEW"/>
        <tooltip>New Model</tooltip>
      </object>
      <object class="tool" name="MAIN_TOOL_OPEN">
        <bitmap stock_id="wxART_FILE_OPEN"/>
        <tooltip>Open Model File</tooltip>
      </object>
      <object class="tool" name="MAIN_TOOL_SAVE">
        <bitmap stock_id="wxART_FILE_SAVE"/>
        <tooltip>Save Model</tooltip>
      </object>
      <object class="tool" name="MAIN_TOOL_SAVEAS">
        <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        <tooltip>Save Model as</tooltip>
      </object>
      <object class="separator"/>
    </object>
    <object class="wxMenuBar" name="Menubar">
      <object class="wxMenu" name="Menu_File">
        <label>File</label>
        <object class="wxMenuItem" name="MenuItem_New">
          <label>New</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_Open">
          <label>Open</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_Close">
          <label>Close</label>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="MenuItem_Save">
          <label>Save</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_FEM">
        <label>FEM</label>
        <object class="wxMenu">
          <label>Grid</label>
          <object class="wxMenuItem" name="MenuItem_GridAdd">
            <label>Add</label>
          </object>
          <object class="wxMenuItem" name="MenuItem_Grid">
            <label>Show</label>
          </object>
        </object>
        <object class="wxMenuItem" name="MenuItem_Conn">
          <label>Connectivity</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_Prop">
          <label>Property</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_Sec">
          <label>Section</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_Set">
          <label>Item Set</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Utility">
        <label>Utility</label>
        <object class="wxMenu">
          <label>Nodes/Elements</label>
          <object class="wxMenuItem" name="MenuItem_Patch">
            <label>Create Patch</label>
          </object>
        </object>
        <object class="wxMenu" name="MenuItem_Material">
          <label>Material</label>
          <object class="wxMenuItem" name="MenuItem_Material_Interface">
            <label>Interface Material</label>
          </object>
        </object>
        <object class="wxMenu">
          <label>Section</label>
          <object class="wxMenuItem" name="MenuItem_Section">
            <label>Create Section</label>
          </object>
          <object class="wxMenuItem" name="MenuItem_Rebar">
            <label>Create Rebar Group</label>
          </object>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Import">
        <label>Import</label>
        <object class="wxMenuItem" name="MenuItem_ImpMarcDat">
          <label>Marc Input</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_ImpPlain">
          <label>Plain</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Export">
        <label>Export</label>
        <object class="wxMenuItem" name="MenuItem_ExpMarcProc">
          <label>Marc Proc</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_ExpMarcDat">
          <label>Marc Input</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_ExpOpenSees">
          <label>OpenSees</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Post">
        <label>PostProcess</label>
        <object class="wxMenuItem" name="MenuItem_PostResults">
          <label>Results</label>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="MenuItem_PostMarcT16">
          <label>Marc *.t16</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Proc">
        <label>Procedure</label>
        <object class="wxMenuItem" name="MenuItem_Pole">
          <label>Pole Adjustment</label>
        </object>
      </object>
      <object class="wxMenu" name="Menu_Macro">
        <label>Macro</label>
        <object class="wxMenuItem" name="MenuItem_MacroRecord">
          <label>Record</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_MacroStop">
          <label>Stop</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_MacroSave">
          <label>Save</label>
        </object>
        <object class="wxMenuItem" name="MenuItem_MacroLoad">
          <label>Load</label>
        </object>
      </object>
    </object>
    <size>1024,768</size>
    <style>wxDEFAULT_FRAME_STYLE|wxSIMPLE_BORDER|wxFULL_REPAINT_ON_RESIZE</style>
    <object class="wxSplitterWindow">
      <orientation>horizontal</orientation>
      <object class="wxSplitterWindow">
        <object class="wxPanel">
          <style/>
          <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <orient>wxHORIZONTAL</orient>
                <object class="sizeritem">
                  <object class="wxBitmapButton" name="MAIN_TOOL_MODELREFRESH">
                    <bitmap>resource_16_home_png</bitmap>
                    <tooltip>Refresh</tooltip>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxBitmapButton" name="MAIN_TOOL_EXPAND">
                    <bitmap>resource_16_round_plus_png</bitmap>
                    <tooltip>Expand ALL</tooltip>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxBitmapButton" name="MAIN_TOOL_COLLAPSE">
                    <bitmap>resource_16_round_minus_png</bitmap>
                    <tooltip>Collapse All</tooltip>
                  </object>
                </object>
              </object>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
            <object class="sizeritem">
              <object class="wxTreeCtrl" name="ModelTree"/>
              <option>1</option>
              <flag>wxALL|wxEXPAND</flag>
              <border>5</border>
            </object>
          </object>
        </object>
        <orientation>vertical</orientation>
        <object class="wxPanel" name="ModelNoteBookPanel">
          <style/>
        </object>
        <sashpos>1</sashpos>
        <minsize>200</minsize>
      </object>
      <object class="wxPanel">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
        </object>
        <object class="wxStaticBoxSizer">
          <label>Message</label>
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxBitmapButton" name="MAIN_MACRO_RECORD">
                  <tooltip>Start recording</tooltip>
                  <bitmap>resource_16_playback_rec_png</bitmap>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxBitmapButton" name="MAIN_MACRO_STOP">
                  <bitmap>resource_16_playback_stop_png</bitmap>
                  <tooltip>Stop recording</tooltip>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxBitmapButton" name="MAIN_MACRO_SAVE">
                  <bitmap>resource_16_doc_export_png</bitmap>
                  <tooltip>Save Macro to file</tooltip>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxBitmapButton" name="MAIN_MACRO_LOAD">
                  <bitmap>resource_16_doc_import_png</bitmap>
                  <tooltip>Load and Run Macro File</tooltip>
                </object>
              </object>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxTextCtrl" name="TextMessage">
              <style>wxTE_MULTILINE|wxTE_READONLY</style>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
          </object>
        </object>
        <style/>
      </object>
      <sashpos>-1</sashpos>
      <minsize>150</minsize>
    </object>
    <object class="wxStatusBar" name="MAIN_STATUSBAR">
      <fields>3</fields>
      <style/>
    </object>
  </object>
</resource>'''

    resource_16_home_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:0020E53C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:0020E53C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:B31E1E37A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:0020E53C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:51+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:76F10702DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:27+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:B31E1E37A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>"J[\x92\x00\x00\x00\x19tEXtSoftware\x00Adobe ImageR\
eadyq\xc9e<\x00\x00\x00\xf9IDATx\xdab`\xa0%066\x96\x07a|j\x18qI\xe8\xeb\
\xeb\xfb322.\x00\xb1\xff\xff\xff\xef\x00dO\x002\x1d\x80\xf8\xc0\x85\x0b\
\x17\x1ca\xeaX\xb0i\xd6\xd1\xd1\xc9\xff\xf7\xef\xdf\x04$\xa1\x03@\xfc\x01\
\x9bZ\x0c\x03455\xe7\xff\xfd\xfb7\x01MX\x00\x8aq{AUU\x95\x1f\xe8L\x90M\x06\
\x04\x82\xe6\x01\xd0K\x06\xb7o\xdf\xfe\x087@QQQ\x1f\xa8y\x03\x90\xa9@d\xf8\
~\x00\x85\xcb\xfd\xfb\xf7/2\xca\xc9\xc9\xd9\x03\x056\xe0r">C\x808\x81QZ\
Z\xfa?%Q\xcd\xf2\xe7\xcf\x1fPh\x17\xa0K0119 \xf3\x81\xb1r\x00\x8b\xfe\x09\
\xe00\x10\x13\x13\xd3\x07*\xb8\x80,\xf3\xe6\xcd\x1b\x944"""\xf2\x1f\xcd\
\x02\x83W\xaf^]\x84+\x12\x10\x10@Q\xf0\xe1\xc3\x07\x14\x03p\xc9\xc3\xd3\
\x010\xee\xf1\xfa\x15\x97<\xdc\x00`X\xe05\x00\x97<\xf5\x0c \xd7\x0b\x00\
\x01\x06\x00\xa3\xfb_{}\xe9\xa3\x8c\x00\x00\x00\x00IEND\xaeB`\x82'''

    resource_16_round_plus_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:08F9B53C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:08F9B53C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:2C75EB36A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:08F9B53C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:50+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:51914101DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:25+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:2C75EB36A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>8
\xf2\x8f\x00\x00\x00\x19tEXtSoftware\x00Adobe ImageReadyq\xc9e<\x00\x00\
\x01GIDATx\xda\xa4SKj\x84@\x10\x9d\xd6(\x88\xa0\x03\xe2\xc6M\\\x88\x0bA\
\xe2\x0d&7\xd0#\xe4\x089\x827\x98+\xe4\x08z\x83\x1c\xc1 \xb8\x12\xc6l\xdc\
\xc9$\x0bq\xa3v\xaa\x9aqpz\x8c\x93OC\xd1e\xd7\xabW\xaf\xaa\xdb\xcd\xe6\x9f\
\x8b\xf0\x07A\x10\xe8\xb0\xc5\x84\x90\x08v{\x16\xaa(\xa5\x09\xc6\xb2,\xfb\
\\$\xf0}?\x84\xc4\x17p\xb7+E?\x80\xe8)\xcf\xf3\xf4\x82\xc0\xf3<LN~*\x1d\
H\xa2\xa2(RF\xe0\xba\xae\x0e\xc9\x15_\x19\xdb\x00\xc3\x8a\xdb\x93|^\x89\
}\x87\xde8\x8e\xf1\x92\xec\xb2,\xd3\xc9w\x1c\x87\x0f#>f\x04}\xdfG\xb7$\x03\
f\xe98b\x04\xc30\xd8\xbc\xec\x85\x9e\x1fO\xfb\xbc\x1d\x9bX\x96u\x8fW4\x01\
\xeb\xba&\xb7\xd4@\x0e\x9d|\x01\x12\xdeQ\xded\xa6i>\xac%C|7\xc7\xb3j\x86\
a\x1c\xb8G\xc3V\xd34g5\x80\xa1\x0b|\xd54D\xec\xe9\xf9\x0fCLX\x05M\xd3t\xb8\
\xca\xabw\x00\xc3
\xda\xb6}SUu\x07\x83}\xe5\xdf\x81 \x08\xf6Y\xa2\xa2(!2\xfe\xe2?\x8a\xba\
\xaeK/NdY\x0e%I:\x82\xd1\x15;"\xee[ZQ\x14u\x90\xb6\x07;\x80\xd1\x99\xe1\
\xf7\x1e\xe3s\xfc\x97\x00\x03\x00f\x84\x91CU\x00\xdfk\x00\x00\x00\x00IE\
ND\xaeB`\x82'''

    resource_16_round_minus_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:09F9B53C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:09F9B53C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:2D75EB36A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:09F9B53C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:50+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:52914101DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:25+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:2D75EB36A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>\xc7\x90{u\x00\x00\x00\x19tEXtSoftware\x00Adobe Ima\
geReadyq\xc9e<\x00\x00\x01\x1eIDATx\xda\xa4R1\x8e\x82P\x10\xfd\x1f\x16J\
0!44RQ\x90\x10\xb9\xc1\x1eAJK\x8f\xe0\x11\xb8\x81W\xd8#\xe0M0$d;\xd9\x86\
V-(6\x01\xfe\xbe\xf9\x91\x0d\x1aE\xd0I^\xfe\xc0\xcc{3\xe63\xf6\xa6\xf1\
\xdb\x1fa\x18\x9a8b\xcey\x84\xd3\xed\x85
!DB\xb14M\xcfw\x05\x82 X\x82\xf8\x05w6P\xf4\x04\xa1u\x96e\xbb+\x01\xdf\
\xf7\x89\x9c\x8cm\x1d"Q\x9e\xe7;)\xe0y\x9e\x09r\xf1\xa4\xf2\xbdN\xdc\x0f\
\xf2\xda\xb6\x8d\x27\x92\xd9%?\x96\x02u]G/.!\x92\x02M\xd3\xfcO\x9b\xa6\x0f\
\x9c\x06\xee>\xbbl\x83\xcc\xe5\x8e\xe3\xcciE]BY\x96\xfcYYpD\xe7+ \xfc\xe0
\xac\x83m\xdb\x8b!2\xe2\x9f\xfd|Y\xcd\xb2\xac\xc3\xcd\xa3\x19kE7D\xba\xd3\
\xe6\x05\x81Dv`\x18\x86\x89UN~\x07\x8a\xa2\xb8*y\xbf0UU\xbf1\xdd\x15\xc0\
FbUU\xd5\xfeJR\xd7\xf5\xa5\xa6iG@\x0c\xe0Hy\x0f\xfbB\x27&Z\xdb\x02\x07@\
\xf4@\xdf[\x8a\xf7\xf3\xff\x04\x18\x00\xee?\x98pk\xd6\x27\x17\x00\x00\x00\
\x00IEND\xaeB`\x82'''

    resource_16_playback_rec_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:60A3C23C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:60A3C23C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:B4B2F336A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:60A3C23C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:50+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:856D6501DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:26+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:B4B2F336A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>;\x189\x98\x00\x00\x00\x19tEXtSoftware\x00Adobe Ima\
geReadyq\xc9e<\x00\x00\x00\xc9IDATx\xdab`\x18\xf2\x80\x11\x9b\xa0\xbe\xbe\
~=##c\x01\x10\x0b\x80\xf8\xff\xff\xff\xff\x00\xc4\x13.^\xbc\xd8H\xd0\x00\
mm\xed\xf3@\x8d\x06\xd8\x0c\x06\x1ar\xe1\xea\xd5\xab\x86\xc8b\xcc\xc8\x1c\
55\xb5z\xa0\xa2\x88\xff\xfe1\xe0\xc0\x12\xc2\xc2\xc2\x0co\xdf\xbe=\x88\
\xd5\x05\x8a\x8a\x8a\xef\x81\x94\x00\x01o\xb8\xff\xbe \x8c\xc3\x02cHK\
K\xf3\xff\xfe\xfd[\x80\x88pCQ\xc3\x82\xe4?\x86?\xfeP\x16\x0bBBBDy\xe1\xdd\
\xbbw\x82X\x03\x91\x85\x85\x85\x03\x18P\x0ex\x02\x11\x84;~\xfd\xfau\x10\
g4rpp\x9c\x07R\x068l\xbf\xf0\xe3\xc7\x0fC\x82\xfe\x02\xba\xa4\x9e\x99\x99\
\xf9=\x10\xff\x87\xe2\xf7 1\x86\xe1\x09\x00\x02\x0c\x00\x9d\x1em\xd6\xb8\
\xd8p\xb6\x00\x00\x00\x00IEND\xaeB`\x82'''

    resource_16_playback_stop_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:B03ABC3C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:B03ABC3C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:B1B2F336A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:B03ABC3C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:50+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:DBFF5701DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:26+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:B1B2F336A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>\xcd\xa1\x04\xc5\x00\x00\x00\x19tEXtSoftware\x00Ado\
be ImageReadyq\xc9e<\x00\x00\x00SIDATx\xdab`\x18\xf2\x80\x11\x99c``\xf0\
\x9e\x91\x91Q\x00\x9f\x86\xff\xff\xff\xb8p\xe1\x82 \x8c\xcf\x82,\xf9\xe7\
\xcf\x1f\x01",EQ\x83b\xc0\xef\xdf\xbfI\xf6\x02\x8a\x01\xbf~\xfd\xa2\xcc\
\x00\x8a]0j\x00\xd8\x80\x0f\xe8\xf1\x8c\x05|`\x18^\x00 \xc0\x00\xc0\x06\
$\xaf\xdf}\xf6\x00\x00\x00\x00IEND\xaeB`\x82'''

    resource_16_doc_export_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:7E1DF93C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:7E1DF93C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:07494237A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:7E1DF93C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:51+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:BBDFF102DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:28+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:07494237A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>\xa4\xb9T\xf4\x00\x00\x00\x19tEXtSoftware\x00Adobe \
ImageReadyq\xc9e<\x00\x00\x01?IDATx\xda\x94SK\x8a\x840\x10M\xc4\x85 hoD\
\x11\x04\xdd\x09\x82\x8cG\x98\x9b8\x27\x99\xa3\x8c\xb9A\x1f\xc1\x1b\xe8\
\xc6\x8d\x1b{\x14\xdc\xb8\x18\x05Q\x17~&%\xd88\xd3\xed\xa7\x0b*1\xa6\xf2\
\xf2\xaa\xea\x05;\x8e#"\x84n\xd4/h\xdb\xbc \x08>\x9em0\xd34\xa1a\x18.\xd4\
\xd1\x8e\xbb\xb6m=\x03\xc00X\x965\xa1s\xe6EQ\xf4\x87\x09\x03\xc3\xc1\xed\
\x8b\x97\xd4u\xd34?\xd7\x00\xec\x02p`%\xc6X\x8f\xe3\xb8\xfa\xbf1\x03\xf4\
}\x04\x10&IR\x19\x86\x01\xa9\xba\xf4\x9b\x9ce\x007\x87\x00\xb0\x8a\xf3\
4MCY\x96\x91#\x80\x92a\x18=M\xd3\x99\xb6\xaa\xaa\xe2*\xce\xa3k\x94\xe79\
\xd9\x03\xb8B{\x15E)a1\x8e\xe3CGdY\xdeep+\x8a\xe2[\x92\xa4\xdd\xb6n\x02\
P\x81\xe9\x27:\xe4\xceB\x12\x04\xe1\x99\x90\x80\xba\x0euXdN\xd3\xf0\xef
\xc4\xd8\xad\xaa\x8a\xcc\x00<\xcfo)\xb1\xa4L\xaet\xf6\x9b\xa6!K\x1c\x1c\
\xae\xeb\x9a\xdc\xa5\xccq\xdc\x91\x94\xfd\xae\xeb\xde!\x0e\x0e\xb7mK^U\xe2\
\x1b\xcb\xb2"\x05\xc10?<&\x9a\xe7\xcf\xc1s\x86\xa2BMB\x904\xad\x85\xb1\xfc\
\xff\x15`\x00\x0d\xac\xcb\xb8gU\x8a\xa7\x00\x00\x00\x00IEND\xaeB`\x82'''

    resource_16_doc_import_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00\x10\x00\x00\x00\x10\x08\x06\x00\x00\x00\
\x1f\xf3\xffa\x00\x00\x0bUiTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<?xp\
acket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 4.2.2-c063\
 53.352624, 2008/07/30-18:12:18        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmpRights="http://ns.adobe.com/xap/1.0/rights/"
   photoshop:AuthorsPosition="Art Director"
   photoshop:Credit="www.gentleface.com"
   photoshop:DateCreated="2010-01-01"
   Iptc4xmpCore:IntellectualGenre="pictogram"
   xmp:MetadataDate="2010-01-03T21:33:13+01:00"
   xmpMM:OriginalDocumentID="xmp.did:7D1DF93C81F7DE119EAB90D7078AF94A"
   xmpMM:DocumentID="xmp.did:7D1DF93C81F7DE119EAB90D7078AF94A"
   xmpMM:InstanceID="xmp.iid:06494237A7F8DE11821CE4B2C7E36D70">
   <Iptc4xmpCore:CreatorContactInfo
    Iptc4xmpCore:CiAdrCity="Prague"
    Iptc4xmpCore:CiAdrPcode="16000"
    Iptc4xmpCore:CiAdrCtry="Czech Republic"
    Iptc4xmpCore:CiEmailWork="ka@gentleface.com"
    Iptc4xmpCore:CiUrlWork="www.gentleface.com"/>
   <xmpMM:History>
    <rdf:Seq>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:7D1DF93C81F7DE119EAB90D7078AF94A"
      stEvt:when="2010-01-02T10:28:51+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:BADFF102DBF7DE11A90083E0A1253BFD"
      stEvt:when="2010-01-02T21:11:28+01:00"
      stEvt:changed="/metadata"/>
     <rdf:li
      stEvt:action="saved"
      stEvt:instanceID="xmp.iid:06494237A7F8DE11821CE4B2C7E36D70"
      stEvt:when="2010-01-03T21:33:13+01:00"
      stEvt:changed="/metadata"/>
    </rdf:Seq>
   </xmpMM:History>
   <dc:title>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">gentleface.com free icon set</rdf:li\
>
    </rdf:Alt>
   </dc:title>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>icon</rdf:li>
     <rdf:li>pictogram</rdf:li>
    </rdf:Bag>
   </dc:subject>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">This is the icon from Gentleface.com\
 free icons set. </rdf:li>
    </rdf:Alt>
   </dc:description>
   <dc:creator>
    <rdf:Seq>
     <rdf:li>Alexander Kiselev</rdf:li>
    </rdf:Seq>
   </dc:creator>
   <dc:rights>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </dc:rights>
   <xmpRights:UsageTerms>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">Creative Commons Attribution Non-Com\
mercial No Derivatives</rdf:li>
    </rdf:Alt>
   </xmpRights:UsageTerms>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>\xe1\xbez\x8a\x00\x00\x00\x19tEXtSoftware\x00Adobe \
ImageReadyq\xc9e<\x00\x00\x01(IDATx\xda\x8cR;n\x840\x10\xc5@\x11\x89\xc2\
 \x84\x84\xa8BC\x83\x84\xe0\x06\x1c!G \x27\x0b7\x08\xb9\xc1\xde\x80m\xa8\
h\xb6\x84\x02mE\xc3\xcfy\x10\x90L\x04\xac-=y<\xcc<\xde|\x88\xb4\x9e(\x8a\
(\xae\x07\xa0K\xe7\x27\xcd\xf3\xfc\x93w\xc8\x9b\xc1\x18\x93\xc6q\xd4\x01\
\xe9\x02I\x10\x04_<\x01\xe1\x1f\xbe\xef3I\xec\xa4EQ,J\x14\xdek\x9af\x0c\
%:\xf06+\xba@\x88\xd8\xf7\xa6i~\xc8j\xcf\xf3(\x02n0\xc3W2\xca\xb2$*\xef\
p]\x97\xf5}\x9f\xc8\xb2\x1cO\xd3$D"\xf3\x8f\xb5Qi\xd7u\x1fP\x11\xc3\xbe\
_5uG\xe08\x0e\xdd>\xe0\xefB$\xcb\x14l\xdb>\xed<\x08\x12EQ2\x10\x1e\xeeG\
UUD\xdd\x98\xce\xc6U\xd75\xb1,\xeb\x0e;>
xE\x90\x18\x86A\x87a\x08\x09!\x87\x01*\xe4\x85\x9b\xbc\xb5\xf3\xb5\x11\
\x92\xa0\x84\x0c\xe6\xedj\xbdw\xb4\x9a\xa6\xb1-\x19d\x19\xee\xcbQ\xb6m\xbb\
\xdf\x83\xb9\x1c\xd1\xe4C\x05KM\xaaJE\x93\xb1t\xfb|$~\x03Ol"\x13\xc0s\xce\
\xf9\x15`\x00\x139\xee5\xbb\xbb\xa4\xa1\x00\x00\x00\x00IEND\xaeB`\x82'''

    wx.MemoryFSHandler.AddFile('XRC/MainFrame/MainFrame_xrc', MainFrame_xrc)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_home_png', resource_16_home_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_round_plus_png', resource_16_round_plus_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_round_minus_png', resource_16_round_minus_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_playback_rec_png', resource_16_playback_rec_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_playback_stop_png', resource_16_playback_stop_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_doc_export_png', resource_16_doc_export_png)
    wx.MemoryFSHandler.AddFile('XRC/MainFrame/resource_16_doc_import_png', resource_16_doc_import_png)
    __res.Load('memory:XRC/MainFrame/MainFrame_xrc')

