# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOG1(wx.Dialog):
#!XRCED:begin-block:xrcDIALOG1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOG1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOG1")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.FIGURE_KEY = xrc.XRCCTRL(self, "FIGURE_KEY")
        self.FIGURE_PLOTDATAKEY = xrc.XRCCTRL(self, "FIGURE_PLOTDATAKEY")
        self.FIGURE_PLOTDATASTYLE = xrc.XRCCTRL(self, "FIGURE_PLOTDATASTYLE")
        self.FIGURE_PLOTDATATYPE = xrc.XRCCTRL(self, "FIGURE_PLOTDATATYPE")
        self.FIGURE_RESET = xrc.XRCCTRL(self, "FIGURE_RESET")
        self.FIGURE_OK = xrc.XRCCTRL(self, "FIGURE_OK")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    figurecreate_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOG1">
    <title>Figure Create</title>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxFlexGridSizer">
              <cols>2</cols>
              <rows>5</rows>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Figure Key</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="FIGURE_KEY">
                  <size>150,20</size>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Plot Data</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="FIGURE_PLOTDATAKEY">
                  <content/>
                  <size>130,20</size>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Style</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="FIGURE_PLOTDATASTYLE">
                  <content/>
                  <size>130,20</size>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Type</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="FIGURE_PLOTDATATYPE">
                  <content>
                    <item>line-one axis</item>
                    <item>line-two axes</item>
                  </content>
                  <size>130,20</size>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="FIGURE_RESET">
                  <label>Reset</label>
                </object>
                <flag>wxALIGN_RIGHT</flag>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="FIGURE_OK">
                  <label>Apply</label>
                </object>
                <flag>wxALIGN_RIGHT</flag>
              </object>
              <vgap>5</vgap>
              <hgap>5</hgap>
            </object>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/figurecreate/figurecreate_xrc', figurecreate_xrc)
    __res.Load('memory:XRC/figurecreate/figurecreate_xrc')

