# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIAG_Rebar(wx.Dialog):
#!XRCED:begin-block:xrcDIAG_Rebar.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIAG_Rebar.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIAG_Rebar")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.REBG_Name = xrc.XRCCTRL(self, "REBG_Name")
        self.REBG_Num = xrc.XRCCTRL(self, "REBG_Num")
        self.REB_1_Name = xrc.XRCCTRL(self, "REB_1_Name")
        self.REB_1_Type = xrc.XRCCTRL(self, "REB_1_Type")
        self.REB_1_Num = xrc.XRCCTRL(self, "REB_1_Num")
        self.REB_1_LD = xrc.XRCCTRL(self, "REB_1_LD")
        self.REB_1_LOC = xrc.XRCCTRL(self, "REB_1_LOC")
        self.REB_1_VD = xrc.XRCCTRL(self, "REB_1_VD")
        self.REB_2_Name = xrc.XRCCTRL(self, "REB_2_Name")
        self.REB_2_Type = xrc.XRCCTRL(self, "REB_2_Type")
        self.REB_2_Num = xrc.XRCCTRL(self, "REB_2_Num")
        self.REB_2_LD = xrc.XRCCTRL(self, "REB_2_LD")
        self.REB_2_LOC = xrc.XRCCTRL(self, "REB_2_LOC")
        self.REB_2_VD = xrc.XRCCTRL(self, "REB_2_VD")
        self.REB_3_Name = xrc.XRCCTRL(self, "REB_3_Name")
        self.REB_3_Type = xrc.XRCCTRL(self, "REB_3_Type")
        self.REB_3_Num = xrc.XRCCTRL(self, "REB_3_Num")
        self.REB_3_LD = xrc.XRCCTRL(self, "REB_3_LD")
        self.REB_3_LOC = xrc.XRCCTRL(self, "REB_3_LOC")
        self.REB_3_VD = xrc.XRCCTRL(self, "REB_3_VD")
        self.REB_4_Name = xrc.XRCCTRL(self, "REB_4_Name")
        self.REB_4_Type = xrc.XRCCTRL(self, "REB_4_Type")
        self.REB_4_Num = xrc.XRCCTRL(self, "REB_4_Num")
        self.REB_4_LD = xrc.XRCCTRL(self, "REB_4_LD")
        self.REB_4_LOC = xrc.XRCCTRL(self, "REB_4_LOC")
        self.REB_4_VD = xrc.XRCCTRL(self, "REB_4_VD")
        self.REB_5_Name = xrc.XRCCTRL(self, "REB_5_Name")
        self.REB_5_Type = xrc.XRCCTRL(self, "REB_5_Type")
        self.REB_5_Num = xrc.XRCCTRL(self, "REB_5_Num")
        self.REB_5_LD = xrc.XRCCTRL(self, "REB_5_LD")
        self.REB_5_LOC = xrc.XRCCTRL(self, "REB_5_LOC")
        self.REB_5_VD = xrc.XRCCTRL(self, "REB_5_VD")
        self.REB_6_Name = xrc.XRCCTRL(self, "REB_6_Name")
        self.REB_6_Type = xrc.XRCCTRL(self, "REB_6_Type")
        self.REB_6_Num = xrc.XRCCTRL(self, "REB_6_Num")
        self.REB_6_LD = xrc.XRCCTRL(self, "REB_6_LD")
        self.REB_6_LOC = xrc.XRCCTRL(self, "REB_6_LOC")
        self.REB_6_VD = xrc.XRCCTRL(self, "REB_6_VD")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    rebargroup_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIAG_Rebar">
    <title>Rebar Group Editor</title>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <label>Settings</label>
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>5</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Name</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REBG_Name"/>
              </object>
              <object class="spacer">
                <size>0,0</size>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Number of Layer</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REBG_Num"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <label>Reinforcement</label>
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>12</rows>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Name</label>
                  <style>wxALIGN_CENTRE</style>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Type</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Number</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Lateral Distance</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Location</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Vertical Distance</label>
                </object>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
            <flag>wxALL|wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_1_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_1_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_1_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_1_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_1_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_1_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_2_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_2_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_2_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_2_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_2_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_2_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_3_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_3_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_3_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_3_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_3_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_3_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_4_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_4_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_4_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_4_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_4_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_4_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_5_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_5_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_5_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_5_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_5_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_5_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
          <object class="spacer">
            <size>5,5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>6</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_6_Name"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_6_Type">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_6_Num"/>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_6_LD"/>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="REB_6_LOC">
                  <content>
                    <item>Bottom|Middle</item>
                    <item>Top|Middle</item>
                    <item>Bottom|Left</item>
                    <item>Bottom|Right</item>
                    <item>Top|Left</item>
                    <item>Top|Right</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="REB_6_VD"/>
              </object>
              <vgap>3</vgap>
              <hgap>3</hgap>
            </object>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/rebargroup/rebargroup_xrc', rebargroup_xrc)
    __res.Load('memory:XRC/rebargroup/rebargroup_xrc')

