# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOG1(wx.Dialog):
#!XRCED:begin-block:xrcDIALOG1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOG1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOG1")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.UNIT_SYSTEM = xrc.XRCCTRL(self, "UNIT_SYSTEM")
        self.UNIT_CAT = xrc.XRCCTRL(self, "UNIT_CAT")
        self.UNIT_LABEL = xrc.XRCCTRL(self, "UNIT_LABEL")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    unit_Select_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOG1">
    <title>Unit Selector</title>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>2</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>System</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="UNIT_SYSTEM">
                  <content>
                    <item>US</item>
                    <item>SI</item>
                  </content>
                  <size>100,20</size>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Category</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="UNIT_CAT">
                  <content/>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Label</label>
                </object>
                <flag>wxALIGN_CENTRE</flag>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="UNIT_LABEL">
                  <content/>
                </object>
              </object>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL|wxALIGN_CENTRE_HORIZONTAL</flag>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
    </object>
    <style>wxDEFAULT_DIALOG_STYLE|wxDIALOG_MODAL</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/unit_Select/unit_Select_xrc', unit_Select_xrc)
    __res.Load('memory:XRC/unit_Select/unit_Select_xrc')

