# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcDIALOG1(wx.Dialog):
#!XRCED:begin-block:xrcDIALOG1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcDIALOG1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "DIALOG1")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.FILE_EXTENSION_CHOICE = xrc.XRCCTRL(self, "FILE_EXTENSION_CHOICE")
        self.FILE_EXTENSION_INPUT = xrc.XRCCTRL(self, "FILE_EXTENSION_INPUT")
        self.FILE_SELECTION = xrc.XRCCTRL(self, "FILE_SELECTION")
        self.FILE_SELECT_PATH = xrc.XRCCTRL(self, "FILE_SELECT_PATH")
        self.FILE_SELECT_NUM = xrc.XRCCTRL(self, "FILE_SELECT_NUM")
        self.FILE_SELECT_SCAN = xrc.XRCCTRL(self, "FILE_SELECT_SCAN")
        self.FILE_SELECT_APPLY = xrc.XRCCTRL(self, "FILE_SELECT_APPLY")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    plain_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="DIALOG1">
    <title>Select Data Source</title>
    <size>600,400</size>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxFlexGridSizer">
              <cols>4</cols>
              <rows>4</rows>
              <object class="sizeritem">
                <object class="wxStaticText" name="">
                  <label>Extension    </label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxChoice" name="FILE_EXTENSION_CHOICE">
                  <content>
                    <item>*.txt</item>
                    <item>*.csv</item>
                    <item>*.dat</item>
                    <item>*.out</item>
                    <item>Other</item>
                  </content>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText" name="">
                  <label>     Other      </label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxTextCtrl" name="FILE_EXTENSION_INPUT"/>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <label>File Filter</label>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxStaticBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="spacer">
            <size>20,10</size>
          </object>
          <object class="sizeritem">
            <object class="wxGenericDirCtrl" name="FILE_SELECTION">
              <size>500,200</size>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>10</border>
          </object>
          <label>Select data file or folder</label>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxFlexGridSizer">
          <cols>3</cols>
          <rows>2</rows>
          <object class="sizeritem">
            <object class="wxStaticText">
              <label>File/Folder Path    </label>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxTextCtrl" name="FILE_SELECT_PATH">
              <size>350,20</size>
            </object>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticText" name="">
              <label>Total File Number    </label>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxTextCtrl" name="FILE_SELECT_NUM"/>
          </object>
          <object class="spacer">
            <size>0,0</size>
          </object>
          <object class="spacer">
            <size>0,0</size>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="FILE_SELECT_SCAN">
              <label>Scan</label>
            </object>
            <flag>wxRIGHT|wxALIGN_RIGHT</flag>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="FILE_SELECT_APPLY">
              <label>Apply</label>
            </object>
          </object>
        </object>
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/plain/plain_xrc', plain_xrc)
    __res.Load('memory:XRC/plain/plain_xrc')

