# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcLSSFRAME(wx.Dialog):
#!XRCED:begin-block:xrcLSSFRAME.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcLSSFRAME.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "LSSFRAME")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.LD_LOAD_SOURCE = xrc.XRCCTRL(self, "LD_LOAD_SOURCE")
        self.POST_L_ItemSourceLabel = xrc.XRCCTRL(self, "POST_L_ItemSourceLabel")
        self.POST_L_ItemSource = xrc.XRCCTRL(self, "POST_L_ItemSource")
        self.POST_L_ItemSelSingle = xrc.XRCCTRL(self, "POST_L_ItemSelSingle")
        self.POST_L_ItemSingle = xrc.XRCCTRL(self, "POST_L_ItemSingle")
        self.POST_L_ItemSelList = xrc.XRCCTRL(self, "POST_L_ItemSelList")
        self.POST_L_ItemList = xrc.XRCCTRL(self, "POST_L_ItemList")
        self.POST_L_ItemSelSet = xrc.XRCCTRL(self, "POST_L_ItemSelSet")
        self.POST_L_ItemSet = xrc.XRCCTRL(self, "POST_L_ItemSet")
        self.POST_D_ItemSourceLabel = xrc.XRCCTRL(self, "POST_D_ItemSourceLabel")
        self.POST_D_ItemSource1 = xrc.XRCCTRL(self, "POST_D_ItemSource1")
        self.POST_D_ItemSource2 = xrc.XRCCTRL(self, "POST_D_ItemSource2")
        self.POST_D_ItemSelSingle = xrc.XRCCTRL(self, "POST_D_ItemSelSingle")
        self.POST_D_ItemSingle = xrc.XRCCTRL(self, "POST_D_ItemSingle")
        self.POST_D_ItemSelList = xrc.XRCCTRL(self, "POST_D_ItemSelList")
        self.POST_D_ItemList = xrc.XRCCTRL(self, "POST_D_ItemList")
        self.POST_D_ItemSelSet = xrc.XRCCTRL(self, "POST_D_ItemSelSet")
        self.POST_D_ItemSet = xrc.XRCCTRL(self, "POST_D_ItemSet")
        self.POST_LD_QUICKPLOT = xrc.XRCCTRL(self, "POST_LD_QUICKPLOT")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    loadstressstrain_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="LSSFRAME">
    <title>Quick Plot: Load Versus Stress/Strain</title>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>2</cols>
              <rows>2</rows>
              <object class="sizeritem">
                <object class="wxRadioBox" name="LD_LOAD_SOURCE">
                  <label>Load Source</label>
                  <content>
                    <item>Load from time</item>
                    <item>Load From Reactions</item>
                  </content>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
            </object>
            <option>1</option>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Reaction </label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>2</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="POST_L_ItemSourceLabel">
                      <label>Reaction Type</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_L_ItemSource">
                      <content>
                        <item>Reaction Force X</item>
                        <item>Reaction Force Y</item>
                        <item>Reaction Force Z</item>
                        <item>Reaction Moment X</item>
                        <item>Reaction Moment Y</item>
                        <item>Reaction Moment Z</item>
                      </content>
                      <selection>0</selection>
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelSingle">
                      <label>Single Item</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_L_ItemSingle">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelList">
                      <label>Item List</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_L_ItemList">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_L_ItemSelSet">
                      <label>Item Set</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_L_ItemSet">
                      <content/>
                    </object>
                  </object>
                </object>
                <border>5</border>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Stress</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>2</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="POST_D_ItemSourceLabel">
                      <label>Stress Type</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_D_ItemSource1">
                      <content>
                        <item>Stress</item>
                        <item>Total Strain</item>
                        <item>Elastic Strain</item>
                        <item>Plastic Strain</item>
                        <item>Cracking Strain</item>
                      </content>
                      <selection>0</selection>
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="spacer">
                    <size>0,0</size>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_D_ItemSource2">
                      <content>
                        <item>1st Comp</item>
                        <item>2nd Comp</item>
                        <item>3rd Comp</item>
                        <item>Comp 11</item>
                        <item>Comp 22</item>
                        <item>Comp 33</item>
                        <item>Comp 12</item>
                        <item>Comp 23</item>
                        <item>Comp 31</item>
                      </content>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelSingle">
                      <label>Single Item</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_D_ItemSingle">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelList">
                      <label>Item List</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="POST_D_ItemList">
                      <size>120,20</size>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxRadioButton" name="POST_D_ItemSelSet">
                      <label>Item Set</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice" name="POST_D_ItemSet">
                      <content/>
                    </object>
                  </object>
                </object>
                <border>5</border>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
          <object class="sizeritem">
            <object class="wxGridSizer">
              <cols>2</cols>
              <rows>2</rows>
              <object class="spacer">
                <size>0,0</size>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="POST_LD_QUICKPLOT">
                  <label>Quick Plot</label>
                </object>
                <flag>wxALIGN_RIGHT</flag>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>0</border>
        <border>5</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/loadstressstrain/loadstressstrain_xrc', loadstressstrain_xrc)
    __res.Load('memory:XRC/loadstressstrain/loadstressstrain_xrc')

