# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcInterfaceMaterial(wx.Dialog):
#!XRCED:begin-block:xrcInterface Material.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcInterface Material.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "Interface Material")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.PARA_tag = xrc.XRCCTRL(self, "PARA_tag")
        self.PARA_gc = xrc.XRCCTRL(self, "PARA_gc")
        self.PARA_vc = xrc.XRCCTRL(self, "PARA_vc")
        self.PARA_vm = xrc.XRCCTRL(self, "PARA_vm")
        self.PARA_q = xrc.XRCCTRL(self, "PARA_q")
        self.PARA_beta1 = xrc.XRCCTRL(self, "PARA_beta1")
        self.PARA_beta2 = xrc.XRCCTRL(self, "PARA_beta2")
        self.PARA_stiff_c = xrc.XRCCTRL(self, "PARA_stiff_c")
        self.PoleProcess = xrc.XRCCTRL(self, "PoleProcess")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    interface_material_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="Interface Material">
    <title> Define Interface Material </title>
    <style>wxDEFAULT_DIALOG_STYLE|wxCAPTION|wxSYSTEM_MENU</style>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Material Type</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxFlexGridSizer">
                  <cols>2</cols>
                  <rows>2</rows>
                  <vgap>11</vgap>
                  <hgap>5</hgap>
                  <growablecols>1</growablecols>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Type</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxChoice">
                      <content>
                        <item>Exponential</item>
                        <item>Bilinear</item>
                        <item>Linear-Exponential</item>
                      </content>
                      <selection>0</selection>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Tag</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_tag">
                      <value>interface_default</value>
                    </object>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxALL|wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Basic Settings</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>4</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Gc</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_gc"/>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Vc</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_vc"/>
                  </object>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>Vm</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_vm"/>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>q</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_q"/>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>20,20</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <label>Basic Settings</label>
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>3</rows>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>beta1</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_beta1"/>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>beta2</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_beta2"/>
                  </object>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxStaticText">
                      <label>stiff_c</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxTextCtrl" name="PARA_stiff_c"/>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>2</cols>
                  <rows>1</rows>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxButton">
                      <label>Help</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="PoleProcess">
                      <label>Process</label>
                    </object>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxALIGN_RIGHT</flag>
          </object>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
        <border>10</border>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/interface_material/interface_material_xrc', interface_material_xrc)
    __res.Load('memory:XRC/interface_material/interface_material_xrc')

